image:
  repository: docker.io/jauderho/yt-dlp
  pullPolicy: Always
  tag: latest

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

ytdlp_jobs:
  - name: "help"
    command: "--help"
    schedule: "0 0 * * *"
  - name: "list"
    command: "--help"
    schedule: "0 0 * * *"

cronjob:
  annotations: {}
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 2

workload:
  main:
    podSpec:
      containers:
        main:
          tty: true
          stdin: true
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false

portal:
  open:
    enabled: false
